window.COURSE_DATA = {
  "generatedAt": "2026-06-10T16:54:17",
  "meta": {
    "importedCourseCount": 49,
    "courseCount": 43,
    "sectionCount": 50,
    "dedupedCount": 6,
    "categories": [
      "专业基础课",
      "专业方向模块",
      "体育锻炼",
      "学科共同课",
      "必修课",
      "跨学科选修",
      "选修课"
    ],
    "departments": [
      "体育教学部",
      "信息管理与工程学院",
      "商学院",
      "数字经济学院",
      "数学学院",
      "经济学院",
      "统计与数据科学学院",
      "计算机与人工智能学院",
      "金融学院"
    ],
    "sourceFiles": [
      "exportResult (36).xls",
      "exportResult (37).xls",
      "exportResult (38).xls",
      "exportResult (39).xls",
      "exportResult (40).xls",
      "exportResult (41).xls",
      "exportResult (42).xls",
      "exportResult (43).xls",
      "exportResult-35.xls"
    ]
  },
  "courses": [
    {
      "id": "course-0382",
      "sourceFile": "exportResult (36).xls",
      "courseNo": "0382",
      "code": "102855",
      "name": "Python程序设计",
      "category": "专业基础课",
      "department": "信息管理与工程学院",
      "arrangement": "陈岗 星期五 8-9 [3-18] 科研实验大楼611（ERP实验教学中心）",
      "teachingClass": "26金融学1班",
      "teacher": "陈岗",
      "teacherDepartment": "信息管理与工程学院",
      "current": 0,
      "limit": 49,
      "seatsLeft": 49,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 3,
      "weekCount": 16,
      "sections": [
        {
          "id": "5-8-9-3-18-1",
          "raw": "陈岗 星期五 8-9 [3-18] 科研实验大楼611（ERP实验教学中心）",
          "weekday": "星期五",
          "dayOrder": 5,
          "startPeriod": 8,
          "endPeriod": 9,
          "weekStart": 3,
          "weekEnd": 18,
          "location": "科研实验大楼611（ERP实验教学中心）",
          "teacher": "陈岗",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-0444",
      "sourceFile": "exportResult (36).xls",
      "courseNo": "0444",
      "code": "102855",
      "name": "Python程序设计",
      "category": "专业基础课",
      "department": "信息管理与工程学院",
      "arrangement": "于长锐 星期一 3-4 [3-18] 机房227",
      "teachingClass": "26金融学2班",
      "teacher": "于长锐",
      "teacherDepartment": "信息管理与工程学院",
      "current": 0,
      "limit": 49,
      "seatsLeft": 49,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 3,
      "weekCount": 16,
      "sections": [
        {
          "id": "1-3-4-3-18-1",
          "raw": "于长锐 星期一 3-4 [3-18] 机房227",
          "weekday": "星期一",
          "dayOrder": 1,
          "startPeriod": 3,
          "endPeriod": 4,
          "weekStart": 3,
          "weekEnd": 18,
          "location": "机房227",
          "teacher": "于长锐",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-0510",
      "sourceFile": "exportResult (36).xls",
      "courseNo": "0510",
      "code": "102855",
      "name": "Python程序设计",
      "category": "专业基础课",
      "department": "计算机与人工智能学院",
      "arrangement": "柴迪 星期一 6-7 [3-18] 机房237",
      "teachingClass": "26公共管理",
      "teacher": "柴迪",
      "teacherDepartment": "计算机与人工智能学院",
      "current": 0,
      "limit": 40,
      "seatsLeft": 40,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 3,
      "weekCount": 16,
      "sections": [
        {
          "id": "1-6-7-3-18-1",
          "raw": "柴迪 星期一 6-7 [3-18] 机房237",
          "weekday": "星期一",
          "dayOrder": 1,
          "startPeriod": 6,
          "endPeriod": 7,
          "weekStart": 3,
          "weekEnd": 18,
          "location": "机房237",
          "teacher": "柴迪",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-0536",
      "sourceFile": "exportResult (36).xls",
      "courseNo": "0536",
      "code": "102855",
      "name": "Python程序设计",
      "category": "专业基础课",
      "department": "信息管理与工程学院",
      "arrangement": "赵晓航 星期三 8-9 [3-18] 科研实验大楼611（ERP实验教学中心）",
      "teachingClass": "26保险精算1班 26保险精算2班",
      "teacher": "赵晓航",
      "teacherDepartment": "信息管理与工程学院",
      "current": 0,
      "limit": 60,
      "seatsLeft": 60,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 3,
      "weekCount": 16,
      "sections": [
        {
          "id": "3-8-9-3-18-1",
          "raw": "赵晓航 星期三 8-9 [3-18] 科研实验大楼611（ERP实验教学中心）",
          "weekday": "星期三",
          "dayOrder": 3,
          "startPeriod": 8,
          "endPeriod": 9,
          "weekStart": 3,
          "weekEnd": 18,
          "location": "科研实验大楼611（ERP实验教学中心）",
          "teacher": "赵晓航",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-0556",
      "sourceFile": "exportResult (36).xls",
      "courseNo": "0556",
      "code": "102855",
      "name": "Python程序设计",
      "category": "专业方向模块",
      "department": "计算机与人工智能学院",
      "arrangement": "韩松乔 星期五 6-7 [1-16] 机房12",
      "teachingClass": "25计算机技术 26计算机技术（第二学位）",
      "teacher": "韩松乔",
      "teacherDepartment": "计算机与人工智能学院",
      "current": 48,
      "limit": 49,
      "seatsLeft": 1,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "5-6-7-1-16-1",
          "raw": "韩松乔 星期五 6-7 [1-16] 机房12",
          "weekday": "星期五",
          "dayOrder": 5,
          "startPeriod": 6,
          "endPeriod": 7,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "机房12",
          "teacher": "韩松乔",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-0562",
      "sourceFile": "exportResult (36).xls",
      "courseNo": "0562",
      "code": "102855",
      "name": "Python程序设计",
      "category": "跨学科选修",
      "department": "计算机与人工智能学院",
      "arrangement": "魏少魁 星期一 6-7 [1-16] 科研实验大楼702（统计教学实验室）",
      "teachingClass": "25人工智能 25人工智能实验班",
      "teacher": "魏少魁",
      "teacherDepartment": "计算机与人工智能学院",
      "current": 0,
      "limit": 61,
      "seatsLeft": 61,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "1-6-7-1-16-1",
          "raw": "魏少魁 星期一 6-7 [1-16] 科研实验大楼702（统计教学实验室）",
          "weekday": "星期一",
          "dayOrder": 1,
          "startPeriod": 6,
          "endPeriod": 7,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "科研实验大楼702（统计教学实验室）",
          "teacher": "魏少魁",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-1993",
      "sourceFile": "exportResult (36).xls",
      "courseNo": "1993",
      "code": "102855",
      "name": "Python程序设计",
      "category": "专业基础课",
      "department": "计算机与人工智能学院",
      "arrangement": "刘畅 星期五 6-7 [9] 机房241 <br>肖程昊 星期五 6-7 [3-8] [10-18] 机房241",
      "teachingClass": "26劳动与社会保障金融学双学位班",
      "teacher": "刘畅,肖程昊",
      "teacherDepartment": "计算机与人工智能学院,计算机与人工智能学院",
      "current": 0,
      "limit": 30,
      "seatsLeft": 30,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 3,
      "weekCount": 16,
      "sections": [
        {
          "id": "5-6-7-9-9-1",
          "raw": "刘畅 星期五 6-7 [9] 机房241",
          "weekday": "星期五",
          "dayOrder": 5,
          "startPeriod": 6,
          "endPeriod": 7,
          "weekStart": 9,
          "weekEnd": 9,
          "location": "机房241",
          "teacher": "刘畅",
          "parsed": true
        },
        {
          "id": "5-6-7-3-8-2",
          "raw": "肖程昊 星期五 6-7 [3-8] [10-18] 机房241",
          "weekday": "星期五",
          "dayOrder": 5,
          "startPeriod": 6,
          "endPeriod": 7,
          "weekStart": 3,
          "weekEnd": 8,
          "location": "[10-18] 机房241",
          "teacher": "肖程昊",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-0764",
      "sourceFile": "exportResult (37).xls",
      "courseNo": "0764",
      "code": "103567",
      "name": "数值计算方法",
      "category": "专业方向模块",
      "department": "信息管理与工程学院",
      "arrangement": "冯银波 星期一 3-5 [1-16] 三教504",
      "teachingClass": "24交叉科学实验班 25大数据1班 25大数据2班",
      "teacher": "冯银波",
      "teacherDepartment": "信息管理与工程学院",
      "current": 112,
      "limit": 53,
      "seatsLeft": 0,
      "credits": 3.0,
      "hours": 48,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "1-3-5-1-16-1",
          "raw": "冯银波 星期一 3-5 [1-16] 三教504",
          "weekday": "星期一",
          "dayOrder": 1,
          "startPeriod": 3,
          "endPeriod": 5,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "三教504",
          "teacher": "冯银波",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-0560",
      "sourceFile": "exportResult (38).xls",
      "courseNo": "0560",
      "code": "102978",
      "name": "计算机组成原理",
      "category": "专业基础课",
      "department": "计算机与人工智能学院",
      "arrangement": "张勇 星期二 11-12 [1-16] 武东路梯九 <br>张勇 星期四 11-12 [1-16] 武东路梯九",
      "teachingClass": "25计算机技术 25信息管理 25电子商务 25大数据1班 25大数据2班 26计算机技术（第二学位）",
      "teacher": "张勇",
      "teacherDepartment": "计算机与人工智能学院",
      "current": 226,
      "limit": 150,
      "seatsLeft": 0,
      "credits": 4.0,
      "hours": 64,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "2-11-12-1-16-1",
          "raw": "张勇 星期二 11-12 [1-16] 武东路梯九",
          "weekday": "星期二",
          "dayOrder": 2,
          "startPeriod": 11,
          "endPeriod": 12,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "武东路梯九",
          "teacher": "张勇",
          "parsed": true
        },
        {
          "id": "4-11-12-1-16-2",
          "raw": "张勇 星期四 11-12 [1-16] 武东路梯九",
          "weekday": "星期四",
          "dayOrder": 4,
          "startPeriod": 11,
          "endPeriod": 12,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "武东路梯九",
          "teacher": "张勇",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-0783",
      "sourceFile": "exportResult (38).xls",
      "courseNo": "0783",
      "code": "102978",
      "name": "计算机组成原理",
      "category": "专业基础课",
      "department": "计算机与人工智能学院",
      "arrangement": "周孟莹 星期三 6-7 [1-16] 教技楼326 <br>周孟莹 星期五 6-7 [1-16] 教技楼326",
      "teachingClass": "25人工智能 25人工智能实验班",
      "teacher": "周孟莹",
      "teacherDepartment": "计算机与人工智能学院",
      "current": 68,
      "limit": 61,
      "seatsLeft": 0,
      "credits": 4.0,
      "hours": 64,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "3-6-7-1-16-1",
          "raw": "周孟莹 星期三 6-7 [1-16] 教技楼326",
          "weekday": "星期三",
          "dayOrder": 3,
          "startPeriod": 6,
          "endPeriod": 7,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "教技楼326",
          "teacher": "周孟莹",
          "parsed": true
        },
        {
          "id": "5-6-7-1-16-2",
          "raw": "周孟莹 星期五 6-7 [1-16] 教技楼326",
          "weekday": "星期五",
          "dayOrder": 5,
          "startPeriod": 6,
          "endPeriod": 7,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "教技楼326",
          "teacher": "周孟莹",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-1212",
      "sourceFile": "exportResult (39).xls",
      "courseNo": "1212",
      "code": "102705",
      "name": "机器学习",
      "category": "必修课",
      "department": "信息管理与工程学院",
      "arrangement": "毕晟 星期四 6-7 [1-16] 三教503",
      "teachingClass": "24经济学拔尖班",
      "teacher": "毕晟",
      "teacherDepartment": "信息管理与工程学院",
      "current": 17,
      "limit": 18,
      "seatsLeft": 1,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "4-6-7-1-16-1",
          "raw": "毕晟 星期四 6-7 [1-16] 三教503",
          "weekday": "星期四",
          "dayOrder": 4,
          "startPeriod": 6,
          "endPeriod": 7,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "三教503",
          "teacher": "毕晟",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-1235",
      "sourceFile": "exportResult (39).xls",
      "courseNo": "1235",
      "code": "102705",
      "name": "机器学习",
      "category": "必修课",
      "department": "信息管理与工程学院",
      "arrangement": "丁婧颖 星期四 3-4 [1-16] 三教601",
      "teachingClass": "24大数据1班",
      "teacher": "丁婧颖",
      "teacherDepartment": "信息管理与工程学院",
      "current": 50,
      "limit": 50,
      "seatsLeft": 0,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "4-3-4-1-16-1",
          "raw": "丁婧颖 星期四 3-4 [1-16] 三教601",
          "weekday": "星期四",
          "dayOrder": 4,
          "startPeriod": 3,
          "endPeriod": 4,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "三教601",
          "teacher": "丁婧颖",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-1248",
      "sourceFile": "exportResult (39).xls",
      "courseNo": "1248",
      "code": "102705",
      "name": "机器学习",
      "category": "必修课",
      "department": "信息管理与工程学院",
      "arrangement": "林倪菲 星期五 3-4 [1-16] 三教104",
      "teachingClass": "24大数据2班",
      "teacher": "林倪菲",
      "teacherDepartment": "信息管理与工程学院",
      "current": 51,
      "limit": 51,
      "seatsLeft": 0,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "5-3-4-1-16-1",
          "raw": "林倪菲 星期五 3-4 [1-16] 三教104",
          "weekday": "星期五",
          "dayOrder": 5,
          "startPeriod": 3,
          "endPeriod": 4,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "三教104",
          "teacher": "林倪菲",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-1282",
      "sourceFile": "exportResult (39).xls",
      "courseNo": "1282",
      "code": "102705",
      "name": "机器学习",
      "category": "必修课",
      "department": "信息管理与工程学院",
      "arrangement": "毕晟 星期四 11-12 [1-16] 三教503",
      "teachingClass": "24交叉科学实验班",
      "teacher": "毕晟",
      "teacherDepartment": "信息管理与工程学院",
      "current": 16,
      "limit": 16,
      "seatsLeft": 0,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "4-11-12-1-16-1",
          "raw": "毕晟 星期四 11-12 [1-16] 三教503",
          "weekday": "星期四",
          "dayOrder": 4,
          "startPeriod": 11,
          "endPeriod": 12,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "三教503",
          "teacher": "毕晟",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-1300",
      "sourceFile": "exportResult (39).xls",
      "courseNo": "1300",
      "code": "102705",
      "name": "机器学习",
      "category": "选修课",
      "department": "计算机与人工智能学院",
      "arrangement": "陈云 星期二 1-2 [1-16] 三教507",
      "teachingClass": "24计算机技术",
      "teacher": "陈云",
      "teacherDepartment": "计算机与人工智能学院",
      "current": 0,
      "limit": 50,
      "seatsLeft": 50,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "2-1-2-1-16-1",
          "raw": "陈云 星期二 1-2 [1-16] 三教507",
          "weekday": "星期二",
          "dayOrder": 2,
          "startPeriod": 1,
          "endPeriod": 2,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "三教507",
          "teacher": "陈云",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-1398",
      "sourceFile": "exportResult (39).xls",
      "courseNo": "1398",
      "code": "102705",
      "name": "机器学习",
      "category": "必修课",
      "department": "数字经济学院",
      "arrangement": "陆子青 星期四 6-7 [1-16] 二教110",
      "teachingClass": "24数字经济拔尖班 24数字经济实验班",
      "teacher": "陆子青",
      "teacherDepartment": "数字经济学院",
      "current": 49,
      "limit": 49,
      "seatsLeft": 0,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "4-6-7-1-16-1",
          "raw": "陆子青 星期四 6-7 [1-16] 二教110",
          "weekday": "星期四",
          "dayOrder": 4,
          "startPeriod": 6,
          "endPeriod": 7,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "二教110",
          "teacher": "陆子青",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-1423",
      "sourceFile": "exportResult (39).xls",
      "courseNo": "1423",
      "code": "102705",
      "name": "机器学习",
      "category": "必修课",
      "department": "计算机与人工智能学院",
      "arrangement": "涂文婷 星期五 8-9 [1-16] 三教407",
      "teachingClass": "24经济数学双学位班",
      "teacher": "涂文婷",
      "teacherDepartment": "计算机与人工智能学院",
      "current": 30,
      "limit": 29,
      "seatsLeft": 0,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "5-8-9-1-16-1",
          "raw": "涂文婷 星期五 8-9 [1-16] 三教407",
          "weekday": "星期五",
          "dayOrder": 5,
          "startPeriod": 8,
          "endPeriod": 9,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "三教407",
          "teacher": "涂文婷",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-1439",
      "sourceFile": "exportResult (39).xls",
      "courseNo": "1439",
      "code": "102705",
      "name": "机器学习",
      "category": "必修课",
      "department": "信息管理与工程学院",
      "arrangement": "林倪菲 星期五 6-7 [1-16] 三教104",
      "teachingClass": "24金融科技拔尖班",
      "teacher": "林倪菲",
      "teacherDepartment": "信息管理与工程学院",
      "current": 22,
      "limit": 22,
      "seatsLeft": 0,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "5-6-7-1-16-1",
          "raw": "林倪菲 星期五 6-7 [1-16] 三教104",
          "weekday": "星期五",
          "dayOrder": 5,
          "startPeriod": 6,
          "endPeriod": 7,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "三教104",
          "teacher": "林倪菲",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-1530",
      "sourceFile": "exportResult (39).xls",
      "courseNo": "1530",
      "code": "102705",
      "name": "机器学习",
      "category": "选修课",
      "department": "计算机与人工智能学院",
      "arrangement": "陈云 星期一 8-9 [1-16] 三教403",
      "teachingClass": "24数量经济 24世界经济 24劳动经济",
      "teacher": "陈云",
      "teacherDepartment": "计算机与人工智能学院",
      "current": 0,
      "limit": 50,
      "seatsLeft": 50,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "1-8-9-1-16-1",
          "raw": "陈云 星期一 8-9 [1-16] 三教403",
          "weekday": "星期一",
          "dayOrder": 1,
          "startPeriod": 8,
          "endPeriod": 9,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "三教403",
          "teacher": "陈云",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-1642",
      "sourceFile": "exportResult (39).xls",
      "courseNo": "1642",
      "code": "102705",
      "name": "机器学习",
      "category": "选修课",
      "department": "计算机与人工智能学院",
      "arrangement": "陈云 星期二 3-4 [1-16] 三教403",
      "teachingClass": "24数学经济双学位班 24经济学基地班",
      "teacher": "陈云",
      "teacherDepartment": "计算机与人工智能学院",
      "current": 0,
      "limit": 50,
      "seatsLeft": 50,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "2-3-4-1-16-1",
          "raw": "陈云 星期二 3-4 [1-16] 三教403",
          "weekday": "星期二",
          "dayOrder": 2,
          "startPeriod": 3,
          "endPeriod": 4,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "三教403",
          "teacher": "陈云",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-1908",
      "sourceFile": "exportResult (39).xls",
      "courseNo": "1908",
      "code": "102705",
      "name": "机器学习",
      "category": "必修课",
      "department": "计算机与人工智能学院",
      "arrangement": "涂文婷 星期五 11-12 [1-16] 三教401",
      "teachingClass": "24投资数学双学位班",
      "teacher": "涂文婷",
      "teacherDepartment": "计算机与人工智能学院",
      "current": 26,
      "limit": 26,
      "seatsLeft": 0,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "5-11-12-1-16-1",
          "raw": "涂文婷 星期五 11-12 [1-16] 三教401",
          "weekday": "星期五",
          "dayOrder": 5,
          "startPeriod": 11,
          "endPeriod": 12,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "三教401",
          "teacher": "涂文婷",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-1233",
      "sourceFile": "exportResult (40).xls",
      "courseNo": "1233",
      "code": "101710",
      "name": "决策仿真",
      "category": "必修课",
      "department": "信息管理与工程学院",
      "arrangement": "邵志芳 星期五 1-2 [1-16] 科研实验大楼511（金融科学实验中心）",
      "teachingClass": "24大数据1班",
      "teacher": "邵志芳",
      "teacherDepartment": "信息管理与工程学院",
      "current": 50,
      "limit": 50,
      "seatsLeft": 0,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "5-1-2-1-16-1",
          "raw": "邵志芳 星期五 1-2 [1-16] 科研实验大楼511（金融科学实验中心）",
          "weekday": "星期五",
          "dayOrder": 5,
          "startPeriod": 1,
          "endPeriod": 2,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "科研实验大楼511（金融科学实验中心）",
          "teacher": "邵志芳",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-1246",
      "sourceFile": "exportResult (40).xls",
      "courseNo": "1246",
      "code": "101710",
      "name": "决策仿真",
      "category": "必修课",
      "department": "信息管理与工程学院",
      "arrangement": "邵志芳 星期五 6-7 [1-16] 科研实验大楼511（金融科学实验中心）",
      "teachingClass": "24大数据2班",
      "teacher": "邵志芳",
      "teacherDepartment": "信息管理与工程学院",
      "current": 51,
      "limit": 51,
      "seatsLeft": 0,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "5-6-7-1-16-1",
          "raw": "邵志芳 星期五 6-7 [1-16] 科研实验大楼511（金融科学实验中心）",
          "weekday": "星期五",
          "dayOrder": 5,
          "startPeriod": 6,
          "endPeriod": 7,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "科研实验大楼511（金融科学实验中心）",
          "teacher": "邵志芳",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-1264",
      "sourceFile": "exportResult (40).xls",
      "courseNo": "1264",
      "code": "101710",
      "name": "决策仿真",
      "category": "选修课",
      "department": "信息管理与工程学院",
      "arrangement": "邵志芳 星期五 3-4 [1-16] 科研实验大楼511（金融科学实验中心）",
      "teachingClass": "24信息管理 24交叉科学实验班",
      "teacher": "邵志芳",
      "teacherDepartment": "信息管理与工程学院",
      "current": 0,
      "limit": 50,
      "seatsLeft": 50,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "5-3-4-1-16-1",
          "raw": "邵志芳 星期五 3-4 [1-16] 科研实验大楼511（金融科学实验中心）",
          "weekday": "星期五",
          "dayOrder": 5,
          "startPeriod": 3,
          "endPeriod": 4,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "科研实验大楼511（金融科学实验中心）",
          "teacher": "邵志芳",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-0161",
      "sourceFile": "exportResult (41).xls",
      "courseNo": "0161",
      "code": "101199",
      "name": "随机过程",
      "category": "选修课",
      "department": "商学院",
      "arrangement": "洪桂毓 星期二 3-5 [1-16] 科研实验大楼B107",
      "teachingClass": "23商务分析实验班",
      "teacher": "洪桂毓",
      "teacherDepartment": "商学院",
      "current": 23,
      "limit": 23,
      "seatsLeft": 0,
      "credits": 3.0,
      "hours": 48,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "2-3-5-1-16-1",
          "raw": "洪桂毓 星期二 3-5 [1-16] 科研实验大楼B107",
          "weekday": "星期二",
          "dayOrder": 2,
          "startPeriod": 3,
          "endPeriod": 5,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "科研实验大楼B107",
          "teacher": "洪桂毓",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-0525",
      "sourceFile": "exportResult (41).xls",
      "courseNo": "0525",
      "code": "101199",
      "name": "随机过程",
      "category": "必修课",
      "department": "数学学院",
      "arrangement": "王清华 星期二 3-4 [1-12] 二教215 <br>王清华 星期四 3-4 [1-12] 二教215",
      "teachingClass": "23金融科技拔尖班",
      "teacher": "王清华",
      "teacherDepartment": "数学学院",
      "current": 16,
      "limit": 20,
      "seatsLeft": 4,
      "credits": 3.0,
      "hours": 48,
      "startWeek": 1,
      "weekCount": 12,
      "sections": [
        {
          "id": "2-3-4-1-12-1",
          "raw": "王清华 星期二 3-4 [1-12] 二教215",
          "weekday": "星期二",
          "dayOrder": 2,
          "startPeriod": 3,
          "endPeriod": 4,
          "weekStart": 1,
          "weekEnd": 12,
          "location": "二教215",
          "teacher": "王清华",
          "parsed": true
        },
        {
          "id": "4-3-4-1-12-2",
          "raw": "王清华 星期四 3-4 [1-12] 二教215",
          "weekday": "星期四",
          "dayOrder": 4,
          "startPeriod": 3,
          "endPeriod": 4,
          "weekStart": 1,
          "weekEnd": 12,
          "location": "二教215",
          "teacher": "王清华",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-1234",
      "sourceFile": "exportResult (41).xls",
      "courseNo": "1234",
      "code": "101199",
      "name": "随机过程",
      "category": "必修课",
      "department": "信息管理与工程学院",
      "arrangement": "郭姗姗 星期一 1-2 [1-12] 三教601 <br>郭姗姗 星期四 6-7 [1-12] 三教601",
      "teachingClass": "24大数据1班",
      "teacher": "郭姗姗",
      "teacherDepartment": "信息管理与工程学院",
      "current": 50,
      "limit": 50,
      "seatsLeft": 0,
      "credits": 3.0,
      "hours": 48,
      "startWeek": 1,
      "weekCount": 12,
      "sections": [
        {
          "id": "1-1-2-1-12-1",
          "raw": "郭姗姗 星期一 1-2 [1-12] 三教601",
          "weekday": "星期一",
          "dayOrder": 1,
          "startPeriod": 1,
          "endPeriod": 2,
          "weekStart": 1,
          "weekEnd": 12,
          "location": "三教601",
          "teacher": "郭姗姗",
          "parsed": true
        },
        {
          "id": "4-6-7-1-12-2",
          "raw": "郭姗姗 星期四 6-7 [1-12] 三教601",
          "weekday": "星期四",
          "dayOrder": 4,
          "startPeriod": 6,
          "endPeriod": 7,
          "weekStart": 1,
          "weekEnd": 12,
          "location": "三教601",
          "teacher": "郭姗姗",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-1247",
      "sourceFile": "exportResult (41).xls",
      "courseNo": "1247",
      "code": "101199",
      "name": "随机过程",
      "category": "必修课",
      "department": "信息管理与工程学院",
      "arrangement": "郭姗姗 星期二 1-2 [1-12] 三教601 <br>郭姗姗 星期四 1-2 [1-12] 三教601",
      "teachingClass": "24大数据2班",
      "teacher": "郭姗姗",
      "teacherDepartment": "信息管理与工程学院",
      "current": 51,
      "limit": 51,
      "seatsLeft": 0,
      "credits": 3.0,
      "hours": 48,
      "startWeek": 1,
      "weekCount": 12,
      "sections": [
        {
          "id": "2-1-2-1-12-1",
          "raw": "郭姗姗 星期二 1-2 [1-12] 三教601",
          "weekday": "星期二",
          "dayOrder": 2,
          "startPeriod": 1,
          "endPeriod": 2,
          "weekStart": 1,
          "weekEnd": 12,
          "location": "三教601",
          "teacher": "郭姗姗",
          "parsed": true
        },
        {
          "id": "4-1-2-1-12-2",
          "raw": "郭姗姗 星期四 1-2 [1-12] 三教601",
          "weekday": "星期四",
          "dayOrder": 4,
          "startPeriod": 1,
          "endPeriod": 2,
          "weekStart": 1,
          "weekEnd": 12,
          "location": "三教601",
          "teacher": "郭姗姗",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-1288",
      "sourceFile": "exportResult (41).xls",
      "courseNo": "1288",
      "code": "101199",
      "name": "随机过程",
      "category": "必修课",
      "department": "信息管理与工程学院",
      "arrangement": "郭姗姗 星期二 3-4 [1-12] 三教605 <br>郭姗姗 星期四 3-4 [1-12] 三教605",
      "teachingClass": "24交叉科学实验班",
      "teacher": "郭姗姗",
      "teacherDepartment": "信息管理与工程学院",
      "current": 16,
      "limit": 16,
      "seatsLeft": 0,
      "credits": 3.0,
      "hours": 48,
      "startWeek": 1,
      "weekCount": 12,
      "sections": [
        {
          "id": "2-3-4-1-12-1",
          "raw": "郭姗姗 星期二 3-4 [1-12] 三教605",
          "weekday": "星期二",
          "dayOrder": 2,
          "startPeriod": 3,
          "endPeriod": 4,
          "weekStart": 1,
          "weekEnd": 12,
          "location": "三教605",
          "teacher": "郭姗姗",
          "parsed": true
        },
        {
          "id": "4-3-4-1-12-2",
          "raw": "郭姗姗 星期四 3-4 [1-12] 三教605",
          "weekday": "星期四",
          "dayOrder": 4,
          "startPeriod": 3,
          "endPeriod": 4,
          "weekStart": 1,
          "weekEnd": 12,
          "location": "三教605",
          "teacher": "郭姗姗",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-1291",
      "sourceFile": "exportResult (42).xls",
      "courseNo": "1291",
      "code": "104235",
      "name": "文本挖掘技术",
      "category": "选修课",
      "department": "计算机与人工智能学院",
      "arrangement": "崔万云 星期五 3-5 [1-16] 三教202",
      "teachingClass": "23信息管理 23电子商务 23计算机技术 23大数据1班 23大数据2班 23交叉科学实验班 24交叉科学实验班",
      "teacher": "崔万云",
      "teacherDepartment": "计算机与人工智能学院",
      "current": 0,
      "limit": 107,
      "seatsLeft": 107,
      "credits": 3.0,
      "hours": 48,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "5-3-5-1-16-1",
          "raw": "崔万云 星期五 3-5 [1-16] 三教202",
          "weekday": "星期五",
          "dayOrder": 5,
          "startPeriod": 3,
          "endPeriod": 5,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "三教202",
          "teacher": "崔万云",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-1327",
      "sourceFile": "exportResult (43).xls",
      "courseNo": "1327",
      "code": "103087",
      "name": "数据分析与可视化",
      "category": "必修课",
      "department": "统计与数据科学学院",
      "arrangement": "季炜杰 星期三 11-12 [1-16] 科研实验大楼711（计算机网络实验室、电子商务实验室）",
      "teachingClass": "24保险精算1班 24保险精算2班 24金融统计双学位1班 24金融统计双学位2班 26数据科学（第二学位）",
      "teacher": "季炜杰",
      "teacherDepartment": "统计与数据科学学院",
      "current": 78,
      "limit": 130,
      "seatsLeft": 52,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "3-11-12-1-16-1",
          "raw": "季炜杰 星期三 11-12 [1-16] 科研实验大楼711（计算机网络实验室、电子商务实验室）",
          "weekday": "星期三",
          "dayOrder": 3,
          "startPeriod": 11,
          "endPeriod": 12,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "科研实验大楼711（计算机网络实验室、电子商务实验室）",
          "teacher": "季炜杰",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-1769",
      "sourceFile": "exportResult (43).xls",
      "courseNo": "1769",
      "code": "103087",
      "name": "数据分析与可视化",
      "category": "必修课",
      "department": "统计与数据科学学院",
      "arrangement": "冯兴东 星期三 6-7 [1-16] 科研实验大楼702（统计教学实验室）",
      "teachingClass": "24工商统计双学位1班 24工商统计双学位2班 24数据科学",
      "teacher": "冯兴东",
      "teacherDepartment": "统计与数据科学学院",
      "current": 80,
      "limit": 80,
      "seatsLeft": 0,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "3-6-7-1-16-1",
          "raw": "冯兴东 星期三 6-7 [1-16] 科研实验大楼702（统计教学实验室）",
          "weekday": "星期三",
          "dayOrder": 3,
          "startPeriod": 6,
          "endPeriod": 7,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "科研实验大楼702（统计教学实验室）",
          "teacher": "冯兴东",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-0010",
      "sourceFile": "exportResult-35.xls",
      "courseNo": "0010",
      "code": "100096",
      "name": "宏观经济学",
      "category": "学科共同课",
      "department": "经济学院",
      "arrangement": "常进雄 星期三 3-4 [1-16] 教技楼327",
      "teachingClass": "24信息管理 24电子商务 24大数据1班 24大数据2班 24交叉科学实验班 25涉外法治实验班 25财经法治卓越班",
      "teacher": "常进雄",
      "teacherDepartment": "经济学院",
      "current": 0,
      "limit": 40,
      "seatsLeft": 40,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "3-3-4-1-16-1",
          "raw": "常进雄 星期三 3-4 [1-16] 教技楼327",
          "weekday": "星期三",
          "dayOrder": 3,
          "startPeriod": 3,
          "endPeriod": 4,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "教技楼327",
          "teacher": "常进雄",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-0050",
      "sourceFile": "exportResult-35.xls",
      "courseNo": "0050",
      "code": "100096",
      "name": "宏观经济学",
      "category": "学科共同课",
      "department": "经济学院",
      "arrangement": "曹林谊 星期三 3-4 [1-16] 教技楼337",
      "teachingClass": "24信息管理 24电子商务 24大数据1班 24大数据2班 24交叉科学实验班 25涉外法治实验班 25财经法治卓越班",
      "teacher": "曹林谊",
      "teacherDepartment": "经济学院",
      "current": 0,
      "limit": 40,
      "seatsLeft": 40,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "3-3-4-1-16-1",
          "raw": "曹林谊 星期三 3-4 [1-16] 教技楼337",
          "weekday": "星期三",
          "dayOrder": 3,
          "startPeriod": 3,
          "endPeriod": 4,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "教技楼337",
          "teacher": "曹林谊",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-0247",
      "sourceFile": "exportResult-35.xls",
      "courseNo": "0247",
      "code": "103181",
      "name": "金融科技导论",
      "category": "必修课",
      "department": "金融学院",
      "arrangement": "星期三 6-7 [1-16] 武东路梯十",
      "teachingClass": "24大数据2班 23金融统计双学位2班 23金融统计双学位1班 24大数据1班",
      "teacher": "",
      "teacherDepartment": "",
      "current": 125,
      "limit": 129,
      "seatsLeft": 4,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "3-6-7-1-16-1",
          "raw": "星期三 6-7 [1-16] 武东路梯十",
          "weekday": "星期三",
          "dayOrder": 3,
          "startPeriod": 6,
          "endPeriod": 7,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "武东路梯十",
          "teacher": "",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-0259",
      "sourceFile": "exportResult-35.xls",
      "courseNo": "0259",
      "code": "100096",
      "name": "宏观经济学",
      "category": "学科共同课",
      "department": "经济学院",
      "arrangement": "李耀华 星期三 3-4 [1-16] 教技楼215",
      "teachingClass": "24信息管理 24电子商务 24大数据1班 24大数据2班 24交叉科学实验班 25涉外法治实验班 25财经法治卓越班",
      "teacher": "李耀华",
      "teacherDepartment": "经济学院",
      "current": 0,
      "limit": 40,
      "seatsLeft": 40,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "3-3-4-1-16-1",
          "raw": "李耀华 星期三 3-4 [1-16] 教技楼215",
          "weekday": "星期三",
          "dayOrder": 3,
          "startPeriod": 3,
          "endPeriod": 4,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "教技楼215",
          "teacher": "李耀华",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-0368",
      "sourceFile": "exportResult-35.xls",
      "courseNo": "0368",
      "code": "103569",
      "name": "优化理论与算法II",
      "category": "选修课",
      "department": "信息管理与工程学院",
      "arrangement": "刘逸诚 星期一 8-9 [1-16] 三教404",
      "teachingClass": "24大数据1班 24大数据2班 24交叉科学实验班",
      "teacher": "刘逸诚",
      "teacherDepartment": "信息管理与工程学院",
      "current": 0,
      "limit": 53,
      "seatsLeft": 53,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "1-8-9-1-16-1",
          "raw": "刘逸诚 星期一 8-9 [1-16] 三教404",
          "weekday": "星期一",
          "dayOrder": 1,
          "startPeriod": 8,
          "endPeriod": 9,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "三教404",
          "teacher": "刘逸诚",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-0418",
      "sourceFile": "exportResult-35.xls",
      "courseNo": "0418",
      "code": "101783",
      "name": "体育锻炼",
      "category": "体育锻炼",
      "department": "体育教学部",
      "arrangement": "黄文奇 星期五 8-9 [1-16] 武东田径场",
      "teachingClass": "24大数据1班",
      "teacher": "黄文奇",
      "teacherDepartment": "体育教学部",
      "current": 50,
      "limit": 55,
      "seatsLeft": 5,
      "credits": 0.0,
      "hours": 32,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "5-8-9-1-16-1",
          "raw": "黄文奇 星期五 8-9 [1-16] 武东田径场",
          "weekday": "星期五",
          "dayOrder": 5,
          "startPeriod": 8,
          "endPeriod": 9,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "武东田径场",
          "teacher": "黄文奇",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-0428",
      "sourceFile": "exportResult-35.xls",
      "courseNo": "0428",
      "code": "101783",
      "name": "体育锻炼",
      "category": "体育锻炼",
      "department": "体育教学部",
      "arrangement": "雷正方 星期五 8-9 [1-16] 武东田径场",
      "teachingClass": "24大数据2班",
      "teacher": "雷正方",
      "teacherDepartment": "体育教学部",
      "current": 51,
      "limit": 55,
      "seatsLeft": 4,
      "credits": 0.0,
      "hours": 32,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "5-8-9-1-16-1",
          "raw": "雷正方 星期五 8-9 [1-16] 武东田径场",
          "weekday": "星期五",
          "dayOrder": 5,
          "startPeriod": 8,
          "endPeriod": 9,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "武东田径场",
          "teacher": "雷正方",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-0937",
      "sourceFile": "exportResult-35.xls",
      "courseNo": "0937",
      "code": "100096",
      "name": "宏观经济学",
      "category": "学科共同课",
      "department": "经济学院",
      "arrangement": "严冬 星期三 3-4 [1-16] 教技楼335",
      "teachingClass": "24信息管理 24电子商务 24大数据1班 24大数据2班 24交叉科学实验班 25涉外法治实验班 25财经法治卓越班",
      "teacher": "严冬",
      "teacherDepartment": "经济学院",
      "current": 0,
      "limit": 40,
      "seatsLeft": 40,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "3-3-4-1-16-1",
          "raw": "严冬 星期三 3-4 [1-16] 教技楼335",
          "weekday": "星期三",
          "dayOrder": 3,
          "startPeriod": 3,
          "endPeriod": 4,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "教技楼335",
          "teacher": "严冬",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-1231",
      "sourceFile": "exportResult-35.xls",
      "courseNo": "1231",
      "code": "103174",
      "name": "高维数据分析",
      "category": "选修课",
      "department": "信息管理与工程学院",
      "arrangement": "袁洪松 星期五 11-13 [1-16] 三教104",
      "teachingClass": "24信息管理 24电子商务 24大数据1班 24大数据2班 24交叉科学实验班",
      "teacher": "袁洪松",
      "teacherDepartment": "信息管理与工程学院",
      "current": 0,
      "limit": 70,
      "seatsLeft": 70,
      "credits": 3.0,
      "hours": 48,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "5-11-13-1-16-1",
          "raw": "袁洪松 星期五 11-13 [1-16] 三教104",
          "weekday": "星期五",
          "dayOrder": 5,
          "startPeriod": 11,
          "endPeriod": 13,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "三教104",
          "teacher": "袁洪松",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-1236",
      "sourceFile": "exportResult-35.xls",
      "courseNo": "1236",
      "code": "103184",
      "name": "计算机网络",
      "category": "选修课",
      "department": "信息管理与工程学院",
      "arrangement": "陈岗 星期二 3-4 [1-16] 三教404",
      "teachingClass": "24信息管理 24电子商务 24大数据1班 24大数据2班",
      "teacher": "陈岗",
      "teacherDepartment": "信息管理与工程学院",
      "current": 0,
      "limit": 53,
      "seatsLeft": 53,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "2-3-4-1-16-1",
          "raw": "陈岗 星期二 3-4 [1-16] 三教404",
          "weekday": "星期二",
          "dayOrder": 2,
          "startPeriod": 3,
          "endPeriod": 4,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "三教404",
          "teacher": "陈岗",
          "parsed": true
        }
      ]
    },
    {
      "id": "course-1239",
      "sourceFile": "exportResult-35.xls",
      "courseNo": "1239",
      "code": "105352",
      "name": "货币银行学（选修）",
      "category": "选修课",
      "department": "金融学院",
      "arrangement": "陈雨恬 星期一 6-7 [1-16] 三教602",
      "teachingClass": "24信息管理 24电子商务 24大数据1班 24大数据2班",
      "teacher": "陈雨恬",
      "teacherDepartment": "金融学院",
      "current": 0,
      "limit": 100,
      "seatsLeft": 100,
      "credits": 2.0,
      "hours": 32,
      "startWeek": 1,
      "weekCount": 16,
      "sections": [
        {
          "id": "1-6-7-1-16-1",
          "raw": "陈雨恬 星期一 6-7 [1-16] 三教602",
          "weekday": "星期一",
          "dayOrder": 1,
          "startPeriod": 6,
          "endPeriod": 7,
          "weekStart": 1,
          "weekEnd": 16,
          "location": "三教602",
          "teacher": "陈雨恬",
          "parsed": true
        }
      ]
    }
  ]
};
